### ISSUE TITLE
Не привязываться бизнес логикой на стили

### ISSUE THREAD

**Issue by dustyo-O** [yevtukov/diploma-js-in-browser#12]
Например, вот тут
https://github.com/yevtukov/diploma-js-in-browser/blob/fae3722ef5f1cf2e92d05092100607f53e0f298b/js/solution.js#L82

Это делает очень скользкой и зависящей от стилей работу приложеньки. Лучше контролировать состояние приложения переменными, внешний вид следует жестко отделить от бизнес логики

Аналогичные плохие места
https://github.com/yevtukov/diploma-js-in-browser/blob/fae3722ef5f1cf2e92d05092100607f53e0f298b/js/solution.js#L157
https://github.com/yevtukov/diploma-js-in-browser/blob/fae3722ef5f1cf2e92d05092100607f53e0f298b/js/solution.js#L274
https://github.com/yevtukov/diploma-js-in-browser/blob/fae3722ef5f1cf2e92d05092100607f53e0f298b/js/solution.js#L413

Возможно, есть и другие привязки к внешнему виду - их всех следует убрать

**Comment by yevtukov** [comment]
Поясните, пжл, что значит бизнес логика и какой переменной можно заменить, например вот это:
 if (image.style.display == 'none')

**Comment by dustyo-O** [comment]
бизнес логика - это основные алгоритмы и сценарии в твоем приложении. Грубо говоря то, как оно работает. Это не должно быть завязано никак на css.

Заменить можно любой переменной в глобальном пространстве, например

**Comment by yevtukov** [comment]
Про бизнес логику понял. Пасиб. Про переменные не совсем. На ум приходит использование атрибутов. Или есть более простой способ?
