### ISSUE TITLE
Оторвать работу со style везде, где возможно.

### ISSUE THREAD

**Issue by dustyo-O** [yevtukov/diploma-js-in-browser#13]
Ожидается использование CSS классов в местах вроде
https://github.com/yevtukov/diploma-js-in-browser/blob/fae3722ef5f1cf2e92d05092100607f53e0f298b/js/solution.js#L134-L170

Следует пройтись по коду и во всех возможных местах добавлять/удалять классы.

Пример места, где это невозможно - https://github.com/yevtukov/diploma-js-in-browser/blob/fae3722ef5f1cf2e92d05092100607f53e0f298b/js/solution.js#L28 (значение стиля тут вычисляется)

Чаще всего оторвать .style будет возможно

**Comment by yevtukov** [comment]
Я правильно понимаю, что придется создать много новых css классов? Для display none, display inline block, z-index 10, z-index 20 и т.д.? Тогда, при всём уважении, считаю, что это только усложнит код. Придется постоянно проверять классы, потом удалять одни и добавлять другие. Если так, то нужно было в задании прописать, что использование style допускается только в крайних случаях. А сейчас нигде в задании не указано, что ожидается использование css классов, а использование style нежелательно.

**Comment by dustyo-O** [comment]
классы, как бы плохо их не использовать, упростят код по сравнению с использованием инлайновых стилей. Инлайновые стили в принципе плохая идея, усложняющая поддержку и развитие продукта.

Тут дело не в уважении, а в правильной архитектуре. Давай сделаем классы и посмотрим, что получится.
